name:                cardano-addresses-cli
version:             3.6.0
github:              input-output-hk/cardano-addresses
license:             Apache-2.0
author:              IOHK
maintainer:          operations@iohk.io
copyright:           2021 IOHK
synopsis:            Utils for constructing a command-line on top of cardano-addresses.
category:            Cardano

description: |
  Please see the README on GitHub at <https://github.com/input-output-hk/cardano-addresses>

extra-source-files:
  ./schemas/address-inspect.json

dependencies:
- base >= 4.7 && < 5

flags:
  release:
    description: Compile executables for a release.
    default: False
    manual: True

library:
  source-dirs: lib
  ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-redundant-constraints
  when:
  - condition: flag(release)
    ghc-options:
    - -Werror
  default-extensions:
  - NoImplicitPrelude
  dependencies:
  - aeson
  - aeson-pretty
  - ansi-terminal
  - bech32
  - bytestring
  - cardano-addresses
  - cardano-crypto
  - code-page
  - extra
  - fmt
  - mtl >= 2.2.2 && < 2.3
  - optparse-applicative
  - process
  - safe
  - template-haskell
  - text

executables:
  cardano-address:
    main: Main.hs
    source-dirs: exe
    ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cardano-addresses
    - cardano-addresses-cli
    when:
    - condition: 'flag(release) && !impl(ghcjs) && !os(ghcjs)'
      ghc-options:
      - -Werror
      - -static
      - -O2
      cc-options: -static
      ld-options: -static -pthread

tests:
  unit:
    source-dirs: test
    main: Main.hs
    default-extensions:
    - NoImplicitPrelude
    ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: flag(release)
      ghc-options:
      - -Werror
    - condition: '!(impl(ghcjs) || os(ghcjs))'
      cpp-options: -DHJSONSCHEMA
      dependencies:
      - hjsonschema >= 1.10.0
    build-tools:
    - hspec-discover
    - cardano-address
    dependencies:
    - aeson
    - bech32
    - bech32-th
    - bytestring
    - cardano-addresses
    - cardano-addresses-cli
    - containers
    - hspec
    - process
    - QuickCheck >= 2.14.2
    - string-interpolate
    - temporary
    - text
