sudo: required
language: c

os: linux
dist: xenial

env:
 - GHCVER=8.6.5
 - GHCVER=8.8.1

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-3.0 ghc-$GHCVER
 - export PATH=/opt/cabal/bin:/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-3.0 update

script:
 - bash scripts/hlint.sh
 - bash scripts/stylish-haskell.sh
 - cabal-3.0 configure --enable-tests
 - cabal-3.0 check
 - cabal-3.0 build all
 - cabal-3.0 test all --test-show-details=streaming
 - cabal-3.0 haddock all
 - cabal-3.0 sdist all
