/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Command-Line',
      collapsed: true,
      items: [
        'how-to-generate-a-recovery-phrase-phraseprv',
        'how-to-generate-a-root-private-key-rootxsk',
        'how-to-generate-a-root-private-key-with-passphrase-rootxsk',
        'how-to-generate-a-wallet-id-based-on-extended-root-or-account-keys-phraseprv',
        'how-to-generate-a-wallet-id-based-on-account-keys-of-shared-wallet-phraseprv',
        'how-to-generate-a-private-policy-key-policyxsk-a-public-policy-key-policyvk-and-its-hash-policyvkh',
        'how-to-generate-a-payment-verification-key-addrxvk',
        'how-to-generate-an-extended-stake-verification-key-stakexvk',
        'how-to-generate-a-non-extended-stake-verification-key-stakevk',
        'how-to-generate-a-hash-for-payment-verification-key-addrxvk',
        'how-to-generate-a-payment-address-from-an-extended-payment-key-paymentaddr',
        'how-to-generate-a-payment-address-from-a-non-extended-payment-key-paymentaddr',
        'how-to-generate-a-payment-address-from-a-payment-key-hash-paymentaddr',
        'how-to-generate-a-delegated-payment-address-ie-base-address-from-an-extended-stake-key-baseaddr',
        'how-to-generate-a-delegated-payment-address-ie-base-address-from-a-non-extended-stake-key-baseaddr',
        'how-to-generate-a-delegated-payment-address-ie-base-address-from-a-stake-key-hash-baseaddr',
        'how-to-generate-a-stake-address-from-an-extended-stake-key-stakeaddr',
        'how-to-generate-a-stake-address-from-a-non-extended-stake-key-stakeaddr',
        'how-to-generate-a-stake-address-from-a-stake-key-hash-stakeaddr',
        'how-to-inspect-address',
        'how-to-generate-a-payment-verification-key-for-shared-wallet-addrsharedvk-stakesharedvk',
        'how-to-construct-a-multisig-script-hash-scripthash',
        'how-to-construct-a-multisig-script-hash-with-timelocks',
        'how-to-validate-a-script',
        'how-to-get-preimage-for-a-script',
        'how-to-generate-a-payment-script-address-from-a-script-hash-scriptaddr',
        'how-to-generate-a-payment-script-address-from-a-script-scriptaddr',
        'how-to-generate-a-delegated-payment-address-ie-base-address-from-a-script-hash-baseaddr',
        'how-to-generate-a-delegated-payment-address-ie-base-address-from-a-script-baseaddr',
        'how-to-generate-a-stake-address-from-a-script-hash-stakeaddr',
        'how-to-generate-a-stake-address-from-a-script-stakeaddr',
        'how-to-generate-drep-keys-drep',
        'how-to-create-script-and-its-hash-from-drep-keys-drep',
        'how-to-generate-cold-committee-keys-cccold',
        'how-to-create-script-and-its-hash-from-cold-committee-keys-drep',
        'how-to-generate-hot-committee-keys-cchot',
        'how-to-create-script-and-its-hash-from-hot-committee-keys-drep',
        'how-to-get-signing-key-and-chain-code-from-an-extended-signing-key-drepsk',
        'how-to-generate-script-validation-preimage-and-script-hash-from-script-composed-of-drep-drepscript',
        'correspondence-between-keys-in-cardano-addresses-and-cardano-cli-keyxsk-keyxvk-keyvk-keyhash',
      ],
    },
    'buildingtesting-from-source-using-nix',
    'override-command-for-cross-compilation',
    'preparation-steps-before-uploading-to-hackage',
    'docker-image',
    'build',
    'run',
    'javascript-support',
    'contributing',
  ],
};

export default sidebars;
