resolver: lts-18.12
compiler: ghc-8.10.7

packages:
- core
- command-line
- jsbits

extra-deps:
- base58-bytestring-0.1.0
- bech32-1.1.1
- bech32-th-1.1.1
- git: https://github.com/input-output-hk/cardano-crypto
  commit: 07397f0e50da97eaa0575d93bee7ac4b2b2576ec
- git: https://github.com/ghcjs/jsaddle
  commit: c4b7c6cebf09447a25105d7c839914d7378bf5a7
  subdirs:
  - jsaddle

- git: https://github.com/input-output-hk/hjsonpointer
  commit: bb99294424e0c5b3c2942c743b545e4b01c12ce8

- git: https://github.com/input-output-hk/hjsonschema
  commit: 1546af7fc267d5eea805ef223dd2b59ac120b784

- hspec-golden-0.1.0.3
- hw-aeson-0.1.8.0
- pretty-simple-4.0.0.0
- prettyprinter-1.7.0
- prettyprinter-ansi-terminal-1.1.2
- string-interpolate-0.3.0.2

allow-newer: true

flags:
  # Using RDRAND instead of /dev/urandom as an entropy source for key
  # generation is dubious. Set the flag so we use /dev/urandom by default.
  cryptonite:
    support_rdrand: false

nix:
  shell-file: nix/stack-shell.nix
