name: Coding Standards

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup Haskell
        uses: haskell-actions/setup@0f8e8c99d88aeb3fbfd523f1ef2c6f762d10d64d # v2.12.1
        with:
          ghc-version: '9.10'
          cabal-version: '3.14'

      - name: Install hlint
        run: |
          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .

  stylish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Check stylish-haskell
        env:
          VERSION: v0.11.0.0
        run: |
          curl -sSL https://raw.github.com/input-output-hk/adrestia/master/templates/haskell/stylish-haskell.sh | sh -s $(git ls-files '*.hs' | grep -v 'jsapi/.*/Main.hs') -i
          if [ -z "$(git status --porcelain)" ]; then
              echo "No style errors detected."
          else
              echo "Style errors detected:"
              git diff
              exit 1
          fi
