name: Pages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  pages:
    name: Pages

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
      with:
        extra-conf: |
          substituters = https://cache.nixos.org https://cache.iog.io
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Build Docusaurus
      run: npm run build

    - name: Build Haddocks
      run: nix build .#haddocks

    - name: Assemble site
      run: |
        mkdir -p site
        cp -r build/. site/
        cp -r result/. site/haddock/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        cname: cardano-addresses.cardano.intersectmbo.org
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
