name: Nix CI

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Enable Nix flakes
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: Enter dev shell and build
        run: |
          nix develop github:input-output-hk/devx#ghc96-iog --no-write-lock-file --refresh --command bash -c "
            cabal update
            cabal build all
            cabal test cardano-addresses:unit
          "
