name: Nix CI

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            target: x86_64-linux
            compiler: ghc96
          - platform: ubuntu-latest
            target: x86_64-linux
            compiler: ghc910
          - platform: ubuntu-latest
            target: x86_64-linux
            compiler: ghc912
          - platform: ubuntu-latest
            target: aarch64-linux
            compiler: ghc96
          - platform: macos-latest
            target: x86_64-darwin
            compiler: ghc96
          - platform: macos-latest
            target: aarch64-darwin
            compiler: ghc96

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GHC and Cabal
        uses: input-output-hk/actions/devx@latest
        with:
          platform: ${{ matrix.platform }}
          target-platform: ${{ matrix.target }}
          compiler-nix-name: ${{ matrix.compiler }}
          iog: true

      - name: Update package index
        run: cabal update

      - name: Build
        run: cabal build all

      - name: Run tests
        run: cabal test cardano-addresses:unit
