name: Nix CI

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull container
        uses: input-output-hk/actions/devx@latest
        with:
          platform: 'x86_64-linux'
          compiler-nix-name: 'ghc96'
          minimal: false
          iog: true

      - name: Build
        shell: devx {0}
        run: |
          cabal update
          cabal build all
          cabal test cardano-addresses:unit
